---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zig
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`zig.joejad.com`)
      kind: Rule
      services:
        - name: zig
          port: 8080
      middlewares:
        - name: default-headers
  tls:
    secretName: local-joejad-tls
