---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: git
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`git.joejad.com`)
      kind: Rule
      services:
        - name: git
          port: 3000
      middlewares:
        - name: default-headers
  tls:
    secretName: local-joejad-tls
