---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paper
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paper.joejad.com`)
      kind: Rule
      services:
        - name: paper
          port: 8000
      middlewares:
        - name: default-headers
  tls:
    secretName: local-joejad-tls
