apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
type: Opaque
data:
    users: ENC[AES256_GCM,data:ckEPFPAC+lV9C9XLwoloYwgCjpbXPOn6FLObd8v/2rgOoGVAueZRajSmZ3BlB8BKa5xaDkNga1Tl41oNNPM5yQ==,iv:6ecgUZK/AhvZtTkCZLDk8P4kSDlMz+BXLGNPSws8IA4=,tag:f3s6GB2ssZ2GkJKYyduEOA==,type:str]
sops:
    age:
        - recipient: age1czrcvq75994t039wsuu4ltdehvaph46t2edr2ehg6jhwuf07za9qnvhzlj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RUxFZktQTkkrUEZnc2wz
            Zjg4MHVvUk9uNjFQRlFEZVA5WjQxdkxMbkhJCmJ0VkxKRWZYRFNWdS81Yk1MZDdN
            TFJpdklnOTByYjZHUk9XVDRuZVJhS28KLS0tIGN3ZEVrTXU4ZVpQVVBRNmwyYW0x
            MU5zdkhlditOd3pna2hlSTlwZyt6YlEK98TZLxrOSciwrcVrcpk3xzCljLAaYG7s
            kF/QpVGLH8EifgcRk1NMNPc1z3+/nEAe3d0bVGgRXIQW5alm2RRM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T20:20:38Z"
    mac: ENC[AES256_GCM,data:rDdz/Qz7TP0EDLwbtO0CmflNYP3RtZ+ZhWD/M/xygbwOL47mZiciR02JfCcZILflNGh/8MrW3PTLtdFarT8IhFyvJoQex5tjU/mHGXX0MhyiTCWgWcUwl++3nRNccKq1mMJot7peJ2BcTFlB+wH1+PJ0YpgttWGlJDdI97HB4SE=,iv:vpKofN5ZphG8C9jjUAO0mpiLxyrjYGo0KpIis/Xybo8=,tag:s3NEJyRNgeHqFM6Q4ukxmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
