---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`uptime.joejad.com`)
      kind: Rule
      services:
        - name: uptime
          port: 3001
      middlewares:
        - name: default-headers
  tls:
    secretName: local-joejad-tls
