---
apiVersion: v1
kind: Service
metadata:
  name: uptime
  namespace: default
spec:
  type: ExternalName
  externalName: 10.47.59.20
  ports:
    - name: http
      port: 3001
      targetPort: 3001
