---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - change
  - external
  - freshrss
  - gitea
  - grafana
  - homepage
  - longhorn
  - mealie
  - pdf
  - postgres
  - traefik
  - vault
