apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:FTiQ38hAROMvy9+vpr4H3CwXGakDfjE8j7GYbvYyzejcMr6tk3xfdw==,iv:C8okZF+p7ikWzt+QeAj7zhELnbP3PnTF9RMcjwFQO9Y=,tag:CkQ6torxn0ZxemOj8nooKA==,type:str]
sops:
    age:
        - recipient: age1czrcvq75994t039wsuu4ltdehvaph46t2edr2ehg6jhwuf07za9qnvhzlj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OVNQOU5pc2RadXZJQ2M3
            dnlyYmFPUVhnNVozdjFrSFhDNjkxa0J4MlRFClhjT211THNKcVFybzFqWFZZcHo3
            T1l2ZlZrS29OZ09HMkpEUzIzWVJ5eHMKLS0tIEROZEowUVd3T0NuOER4RTdyKy8x
            dTRqNG9nTlhSM2xkeXBlaHNoTGZGWUEKrmZAYnq97lWEEk0HpDTWNM2k1Byy5qLY
            uwqupNhFhHh8Wrq2Z1y7uK4gyCLtGeWBM1YVa0NdN7qi0vN/3WaBaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T20:16:55Z"
    mac: ENC[AES256_GCM,data:cF69etmV7gyZX9/C8nHhvrfd/dIZOALLym1EQxnTPwsHU4FgKBgT8rftfS7mtAv7AS0XCfAhGrpNndTsVgNzdDhC3pHd73+/V3zXDRB+dnCupmK/K0x9vmbS1w6EiCXdyKHDMiWqqCayLKBH2gABKdepNltjZ/8cBh8gL78Wks8=,iv:ERSSiaFdmnO51+tEdPBzvV2WM7X8X4nyQ6d2PAZFMnw=,tag:Vvho/9pUMgOm/v8EtJdKSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
