---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - backup
  - cloud
  - git
  - golf
  - home-assistant
  - jellyfin
  - lidarr
  # - ollama
  - opnsense
  - paper
  - prowlarr
  - proxmox
  - qbt
  - radarr
  - readarr
  - scrypted
  - sonarr
  - unifi
  - uptime
  - workout
  - zig
